import "./globals.css";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./context/AuthProvider";
import { NavBar } from "./components/ui/Navbar";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/nextAuthOptions";
import { Container, Theme } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AuthProvider>
          <Theme>
            <Container>
              <NavBar user={session?.user.name} />
              <>{children}</>
            </Container>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
